sudo: required
language: ruby
rvm:
  - 2.4
addons:
  firefox: latest
git:
  depth: 1
branches:
  except:
    - static
    - gh-pages
before_script:
  - bundle exec rake wax:lunr
script:
  - bundle exec jekyll build -d _site/wax
  - bundle exec rake wax:test
