sudo: required
language: ruby
addons:
  chrome: stable
rvm:
  - 2.4
before_script:
  - bundle exec rake wax:pagemaster qatar_collection
  - bundle exec rake wax:lunr
  - bundle exec jekyll build -d _site/wax
script:
  - bundle exec rake wax:test
branches:
  except:
  - gh-pages
