# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Wax'
description:      'Minimal Exhibitions with Jekyll'
url:              ''
baseurl:          '/wax'
copyright:        'Example copyright org, 2019'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink:        'pretty'
sass:
    style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - wax_theme
  - package.json
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  qatar: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'qatar_item' # the layout for the pages to use
    metadata:
      source: 'qatar.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/qatar' # path to the directory of images within `_data`

# --------------------------------------------------------------
# LUNR SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple lunr indexes below (though only one is
# recommended!) by specifying
# a `file` to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:lunr` .
# You can optionally generate a default UI by specifying a UI file
# and running `$ bundle exec rake wax:lunr UI=true`.

lunr_index:
  - file: 'assets/js/lunr-index.json' # file the index will get written to
    ui:   'assets/js/lunr-ui.js' # path to the search UI file
    collections:
      qatar:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - artist
          - location
          - label
          - _date
          - object_type
          - current_location

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'Wax'
        link: '/about/'
      - label: 'Documentation'
        link: 'https://minicomp.github.io/wiki/#/wax/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Exhibits'
    sub:
      - label: 'Inline Parallax Image'
        link: '/exhibits/a/'
      - label: 'Inline Image References'
        link: '/exhibits/b/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Reuse'
    link: '/reuse/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/minicomp/wax'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: 'https://gitter.im/minicomp/wax/'
  logos:
    - img: '/assets/logo.png'
    - img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2r40VYrf2Q5jkJiPGjPkl7xZoHJliwgVtHCLVXmAsRKw0ZudD'
      link: 'https://library.columbia.edu'

# FIN
